name: Run FPL Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This runs the job daily at midnight (optional)

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run the Python script
    - name: Run FPL Pipeline
      run: |
        python main.py

    # Commit changes
    - name: Commit changes
      run: |
        git config --global user.name 'xRayzox'
        git config --global user.email 'wael.hcine@esprit.tn'
        git add data
        git commit -m "Add generated data files" || echo "No changes to commit"

    # Stash any unstaged changes (if any)
    - name: Stash unstaged changes
      run: git stash || echo "No changes to stash"

    # Fetch latest changes and rebase
    - name: Rebase changes
      run: |
        git fetch origin
        git rebase origin/main

    # Push the changes
    - name: Push changes
      run: git push
